server:
  port: 8081
  error:
    include-message: always
    include-binding-errors: always
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/havoc
    username: asphyxia
    password: secret
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  jooq:
    sql-dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: true
    url: jdbc:postgresql://localhost:5432/havoc
    user: asphyxia
    password: secret
havoc:
  app:
    jwtSecret: 9a4f2c8d3b7a1e6f45c8a0b3f267d8b1d4e6f3c8a9d2b5f8e3a9c8b5f6v8a3d9
    jwtExpirationMs: 600000
    jwtRefreshExpirationMs: 180000